# Generated by Django 4.2.1 on 2023-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userteam',
            name='pk_userteam',
        ),
        migrations.RemoveConstraint(
            model_name='userteamrequest',
            name='pk_userteam_request',
        ),
        migrations.RenameField(
            model_name='userteam',
            old_name='teamName',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='userteam',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userteamrequest',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='userteamrequest',
            name='userId',
        ),
        migrations.AddConstraint(
            model_name='userteam',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='pk_userteam'),
        ),
        migrations.AddConstraint(
            model_name='userteamrequest',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='pk_userteam_request'),
        ),
    ]
